### ISSUE TITLE
<img alt="???">

### ISSUE THREAD

**Issue by tomByrer** [lxsmnsyc/solid-use#2]
I'm confused by your `fetch` example:
```js
<img src={result.value.message} alt={result().value.message} />
```
I thought `alt` for for a text description of the image (for blind or folks with slow download speeds).  But you return the image again?
https://yoast.com/image-seo-alt-tag-and-title-tag-optimization/

**Comment by lxsmnsyc** [comment]
This is just a minor issue that is for the demos only.
