### ISSUE TITLE
Would you be open for porting as many functions from vueuse as we can?

### ISSUE THREAD

**Issue by Evertt** [lxsmnsyc/solid-use#4]
Because vueuse is full of useful functions, imo. I already ported `useMouse` and `useEventListener` in my personal project where I'm experimenting with SolidStart. You can see some implementation code [here](https://github.com/Evertt/solid-start/blob/main/src/solid-use/useMouse.ts) and the usage [here](https://github.com/Evertt/solid-start/blob/main/src/routes/mouse.tsx).

And here's a little video showing the result:

https://user-images.githubusercontent.com/1267282/203549400-b2b64cef-500d-4d6e-9f74-57248388f6af.mov

Anyway, so I thought, wouldn't it be nice to just port as many of their utility functions over as we can? What do you think? I'm happy to contribute PRs.

**Comment by lxsmnsyc** [comment]
I believe [solid-primitives](https://github.com/solidjs-community/solid-primitives) has ported many if not all of the capabilities of vueuse and other similar collections like react-use, so I would recommend looking over to it. I just collect unconventional primitives now for solid-use.

**Comment by Evertt** [comment]
Ah thanks, I was not aware of that repo.
